### ISSUE TITLE
Mirror compatibility 

### ISSUE THREAD

**Issue by demonixis** [MidLevel/MLAPI.Relay#4]
Hello,
Is it possible to use this relay with the Mirror framework? If not how to add support for it?
Thanks.

**Comment by TwoTenPvP** [comment]
Yes this can be used with Mirror. As long as you use the RelayTransport instead of the NetworkTransport for all UNET operations.

**Comment by demonixis** [comment]
Great :) What about the dll in the library folder? Do I've to put them into my Unity project too? We've maybe a better place to talk about that?
